name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build
      run: mvn -B clean package

    - name: Test
      run: mvn -B test
      
    - name: Debug
      run: |
        pwd
        ls -la
        ls -la target
      
    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      shell: bash
      run: |
        docker build -t api-demo:latest -f Dockerfile-demo .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker tag api-demo tairitsu86/api-demo
        docker push tairitsu86/api-demo:latest
        
        
        
